import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
if (typeof window !== 'undefined') {
  let myVariable = localStorage.getItem('dark') 
  if(myVariable==="False"){
    document.documentElement.classList.remove('dark');
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark bg-gradient-to-b from-lightPrimaryGradient to-lightSecondaryGradient dark:bg-[#0f0f0f]'>
      <body className=' dark:bg-[#0f0f0f]' >{children}</body>
    </html>
  )
}
